<?php
/**
 * @file
 * Webform Remote Post module.
 *
 * Webform Remote Post is a module that works along the 
 * @link http://drupal.org/project/webform Webform @endlink module.
 * It eases the integration between Webforms and other web 
 * applications.
 */

/**
 * Implements hook_help.
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function webform_remote_post_help($path, $arg) {
  switch ($path) {
    case "admin/help#webform_remote_post":
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Coming soon') . '</p>';
      $output .= '<h3>' . t('Use Cases') . '</h3>';
      $output .= '<p>' . t('more...') . '</p>';
      break;
  }
}

/**
 * Implements hook_menu().
 *
 * @see webform_menu_load()
 */
function webform_remote_post_menu() {
  $items = array();
  
  // Targets list, %webform_menu is an auto-loader wildcard component
  // provided by the webform module (method is webform_menu_load), and it
  // auto-loads a webform node.
  $items['node/%webform_menu/webform/targets'] = array(
    'title' => 'Remote Posts',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('webform_remote_post_targets_form', 1),
    'access callback' => 'user_access',
    'access arguments' => array('admin webform remote posts'),
    'file' => 'includes/webform_remote_post.targets.inc',
    'weight' => 1,
    'type' => MENU_LOCAL_TASK,
  );

  // Delete a target
  $items['node/%webform_menu/webform/targets/%/delete'] = array(
    'title' => 'Delete repost target',
    'load arguments' => array(1),
    'page arguments' => array('webform_remote_post_target_delete_form_submit', 1, 4),
    'access callback' => 'user_access',
    'access arguments' => array('admin webform remote posts'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Respond to a Webform submission being inserted.
 *
 * Note that this hook is called after a submission has already been saved to
 * the database.
 *
 * This is the main purpose of this module, to emit HTTP POSTs based on the
 * saved webform data.
 *
 * @param $node
 *   The Webform node on which this submission was made.
 * @param $submission
 *   The Webform submission that was just inserted into the database.
 * @todo Support of Grid component.
 * @todo Support of File component.
 */
function webform_remote_post_webform_submission_insert($node, $submission) {  
  // Skip draft forms:
  if ($submission->is_draft) {
    return;
  }
  
  // Get this webform node remote targets from the DB:
  $targets = array();
  $targets = db_select('webform_remote_post_targets')
    ->fields('webform_remote_post_targets')
    ->condition('nid', $node->nid)
    ->condition('enabled', 1)
    ->execute()
    ->fetchAllAssoc('tid', PDO::FETCH_ASSOC);

  // Create a map with webform component ID's and the component themselves,
  // handly later on.
  $component_map = array();
  foreach ($node->webform['components'] as $component) {
    $component_map[$component['cid']] = $component;
  }
  
  // Prepare the submission data for remote posting. Creating a two-dimensional
  // array of form field names and the data.
  $payload = array();
  foreach ($submission->data as $cid => $component_data) {
    $payload[$component_map[$cid]['form_key']] = implode(', ', $component_data['value']);
  }
  
  // URL-encode the payload
  $post_data = http_build_query($payload);
  
  // Repost data to each target. Begin by setting the
  // options for drupal_http_request().
  $drupal_http_request_options = array(
    'method' => 'POST',
    'data' => $post_data,
    'timeout' => 15,
    'headers' => array('Content-Type' => 'application/x-www-form-urlencoded'),
  );
  
  // Acceptable server response codes.
  $benign_reponse_codes = array('200', '301', '302', '307');
  
  // Repost data to each target.
  foreach ($targets as $tid => $target) {
    // Where the magic happens:
    $request = drupal_http_request($target['url'], $drupal_http_request_options);
    // Log any errors.
    if (isset($request->code) && !in_array($request->code, $benign_reponse_codes)) {
      $log_msg = 'A remote post to %url by webform node ID %id returned a ';
      $log_msg .= '\'%code\' code, which is a different HTTP response code ';
      $log_msg .= 'than expected. Please make sure that the remote post URL ';
      $log_msg .= 'is correct in the Remote Posts webform settings, and that ';
      $log_msg .= 'the post was received in the remote system.';
      watchdog('webform_remote_post', 
               $log_msg, 
               array('%id'   => $node->nid,
                     '%url'  => $target['url'], 
                     '%code' => $request->code,
                     ), 
               WATCHDOG_WARNING);
    }
  }
}

/**
 * Implements hook_perm().
 */
function webform_remote_post_permission() {
  return array(
    'admin webform remote posts' => array(
      'title' => t('Admin webform remote posts'),
      'description' => t('Grants access to the "Remote Posts" webform settings on all webform content.'),
    ),
  );
}

/**
 * Implements hook_theme()
 *
 *
 * @return array An associative array of theme hook information.
 * @author Enrique Delgado
 */
function webform_remote_post_theme($existing, $type, $theme, $path) {
  $theme = array(
    // webform_remote_posts.targets.inc.
    'webform_remote_post_targets_form' => array(
      'render element' => 'form',
      'file' => 'includes/webform_remote_post.targets.inc',
    ),
  );
  return $theme;
};